name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libasound2-dev libdbus-1-dev
    
    - name: Build
      run: cargo build --verbose
      
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libasound2-dev libdbus-1-dev
    
    - name: Run tests
      run: cargo test --verbose
      
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libasound2-dev libdbus-1-dev
      
      - name: Run clippy
        run: cargo clippy -- -D warnings
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run cargofmt
        run: cargo fmt --all -- --check
